# Generated by Django 2.0.5 on 2018-11-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.SlugField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('publication_date_time', models.DateTimeField()),
                ('currency_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('baseCurrency', models.CharField(max_length=10)),
                ('targetCurrency', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.SlugField(max_length=200)),
            ],
        ),
    ]
