# Generated by Django 2.0.5 on 2018-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='link',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='currencyfeed',
            name='link',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('publication_date_time', 'targetCurrency')},
        ),
    ]
