# Generated by Django 2.0.5 on 2018-11-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20181117_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyfeed',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
